version: "3.7"
services:
  postgres:
    image: postgres:14

    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data

    networks:
      - ${REDE_DOCKER}

    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PG_MAX_CONNECTIONS=500

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  ${POSTGRES_VOLUME}:
    external: true
    name: ${POSTGRES_VOLUME}

networks:
  ${REDE_DOCKER}:
    external: true
    name: ${REDE_DOCKER}
